# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.security=TRACE


# Configuration database server

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

#Configuration Oauth google

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID_GOOGLE}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET_GOOGLE}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

#Configuration Oauth facebook
spring.security.oauth2.client.registration.facebook.client-id=${CLIENT_ID_FACEBOOK}
spring.security.oauth2.client.registration.facebook.client-secret=${CLIENT_SECRET_FACEBOOK}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile,user_photos
spring.security.oauth2.client.registration.facebook.authorization-grant-type=authorization_code


#Configuration to deployment

# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASS}


#Configuration email server
spring.mail.host=${SMTP_SERVER}
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Configuration JWT tokens variable environment
key.auth.token=${SECRET_JWT}

#Configuration for file upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB